# Generated by Django 6.0.3 on 2026-03-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_birthday_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='author',
        ),
    ]
